package com.ea.autoEx.integ.dal.model;

import java.io.Serializable;

public class Job implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_job.id
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_job.job_name
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_job.id
     *
     * @return the value of i_job.id
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_job.id
     *
     * @param id the value for i_job.id
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_job.job_name
     *
     * @return the value of i_job.job_name
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_job.job_name
     *
     * @param jobName the value for i_job.job_name
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }
}