package com.ea.autoEx.integ.dal.dao;

import com.ea.autoEx.integ.dal.model.Job;
import com.ea.autoEx.integ.dal.model.JobCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int countByExample(JobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int deleteByExample(JobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    List<Job> selectByExample(JobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    Job selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int updateByExampleSelective(@Param("record") Job record, @Param("example") JobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int updateByExample(@Param("record") Job record, @Param("example") JobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_job
     *
     * @mbggenerated Mon Aug 25 12:06:56 CST 2014
     */
    int updateByPrimaryKey(Job record);
}