package com.ea.autoEx.integ.dal.dao;

import com.ea.autoEx.integ.dal.model.User;
import com.ea.autoEx.integ.dal.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    int updateByPrimaryKey(User record);
}