package com.ea.autoEx.integ.dal.dbmodel;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.id
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.name
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.psw
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    private String psw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.email
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.age
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_user.validate
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    private Byte validate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.id
     *
     * @return the value of i_user.id
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_user.id
     *
     * @param id the value for i_user.id
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.name
     *
     * @return the value of i_user.name
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_user.name
     *
     * @param name the value for i_user.name
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.psw
     *
     * @return the value of i_user.psw
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public String getPsw() {
        return psw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_user.psw
     *
     * @param psw the value for i_user.psw
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public void setPsw(String psw) {
        this.psw = psw == null ? null : psw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.email
     *
     * @return the value of i_user.email
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_user.email
     *
     * @param email the value for i_user.email
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.age
     *
     * @return the value of i_user.age
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_user.age
     *
     * @param age the value for i_user.age
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_user.validate
     *
     * @return the value of i_user.validate
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public Byte getValidate() {
        return validate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_user.validate
     *
     * @param validate the value for i_user.validate
     *
     * @mbggenerated Wed Jul 16 17:48:16 CST 2014
     */
    public void setValidate(Byte validate) {
        this.validate = validate;
    }
}